### ISSUE TITLE
Wrong fix of import warning

### ISSUE THREAD

**Issue by rintcius** [nwolverson/purescript-suggest#6]
First of all thanks for writing this! This comes in very handy for my lib (which contains generated purescript code)

I was running `pulp build -- --censor-lib --json-errors 2>&1 | ps-suggest --apply` on my lib [here](https://github.com/rintcius/purescript-mathbox) but one warning was not fixed properly: https://github.com/rintcius/purescript-mathbox/blob/master/src/Mathbox/Classes.purs#L150

It changes this line into:
```
import Mathbox.Class.Data.Voxel (JsVoxel, Voxel, VoxelG, mkVoxel, voxelToJs)Voxel
```
instead of 
```
import Mathbox.Class.Data.Voxel (JsVoxel, Voxel, VoxelG, mkVoxel, voxelToJs)
```

**Comment by nwolverson** [comment]
Ah, compiler ranges are wrong at the end of files, maybe it's that. Can maybe special case this one

**Comment by rintcius** [comment]
Ok - FYI I also thought it may have to do with EOF - I tried to workaround it by adding a comment at the end of the file though, but that still gave the same error.

**Comment by nwolverson** [comment]
I do believe the issue at end of files is resolved since the compiler's parser switch, hence closing.
