### ISSUE TITLE
Applying remove import suggestion leaves blank line

### ISSUE THREAD

**Issue by nwolverson** [nwolverson/purescript-suggest#7]
Not sure if this is compiler issue but either way there is the information to fix here

**Comment by kritzcreek** [comment]
deleting a line would make the position info in all the other suggestions invalid though and would have to be tracked

**Comment by nwolverson** [comment]
Suggestion application can already change the line count, no problem, there should already be unit test that does that too - should be able to apply multiple such with no problem.

On the other hand if you are calling from pscid and just actioning one suggestion, without updating the list afterwards, that could be an issue (already) - but presumably it rebuilds after?

**Comment by kritzcreek** [comment]
Oh allright nvm then. Yep applying a suggestion triggers a rebuild
immediately anyway. Thanks for clarifying!

Am 14.02.2017 10:04 nachm. schrieb "Nicholas Wolverson" <
notifications@github.com>:

**Comment by nwolverson** [comment]
Done in 672942a4e47017fc6b5eb0c76a7b06cc7376f9c4, hopefully
